env: sc2

env_args:
  continuing_episode: False
  difficulty: "1"
  game_version: null
  map_name: "2s3z"
  move_amount: 2
  obs_all_health: True
  obs_instead_of_state: False
  obs_last_action: False
  obs_own_health: True
  obs_pathing_grid: False
  obs_terrain_height: False
  obs_timestep_number: False
  reward_death_value: 10
  reward_defeat: -200
  reward_negative_scale: 1 #0.5
  reward_only_positive: False
  reward_scale: False
  # reward_scale_rate: 20
  reward_sparse: False
  reward_win: 200
  replay_dir: "/vol/bitbucket/mt5217/replays"
  replay_prefix: ""
  state_last_action: True
  state_timestep_number: False
  step_mul: 8
  seed: null
  heuristic_ai: False
  heuristic_rest: False
  debug: False
  advance: True  # Challenge - move all units past enemy lines
  advance_easy: True

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000

# Logging
save_model: True # Save the models to disk
save_model_interval: 50000 # Save models after this many timesteps
checkpoint_path: "/vol/bitbucket/mt5217/results/models/qmix__2021-05-28_17-18-07" # Load a checkpoint from this path
# load_step: 0 # Load model trained on this many timesteps (0 if you want only the last one)
save_replay: True # Saving the replay of the model loaded from checkpoint_path
local_results_path: "/vol/bitbucket/mt5217/results"
# evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)